version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-159-112-44.compute-1.amazonaws.com
            database: daa9pu99t433
            user: xxopabmmcnnkyq
            password: eeaf1864cfe2e01d1cafeb4a667d1f3106a72c42ad951ad7dafb4c5f3330ca4e
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true